//! **The defensive half: what a passive monitor on the link can conclude, and
//! when.**
//!
//! This is item 5 in the Open Door Range build order, beside `odr-attack`
//! (`DESIGN.md` §3 and §6), and the crate `DESIGN.md` §5 calls a first-class
//! part of the project rather than an afterthought. The whole of Module 5 of
//! `docs/CURRICULUM.md` lives here: every earlier module replayed from a
//! monitoring position, with the question changed from *can I do this* to
//! *could anybody have noticed*.
//!
//! ```text
//!   credential ──▶ READER ──wire or bus──▶ CONTROLLER ──▶ DOOR
//!                            ▲
//!                        monitor ──▶ Monitor ──▶ RuleSet ──▶ Report ──▶ Score
//! ```
//!
//! # The governing rule
//!
//! **A detector may only see what a passive monitor on the link sees.** Bytes
//! and timing. Not the engine's node configuration, not any key, not the
//! access list, and not the `cause` field that makes `odr-bus`'s own event log
//! a graph. If a detector needs to know something, it infers it from traffic or
//! it accepts that a defender could not have known it either.
//!
//! That rule is the mirror of the one governing `odr-attack`, and it is what
//! makes Module 5 honest. A detector that quietly read world state would score
//! perfectly against every drill and teach nothing, because a defender standing
//! in a riser with an RS-485 dongle does not have world state. The type
//! [`Monitor`] is that rule made structural: there is nowhere in it to put
//! ground truth, and the strongest tests in the suite run a scenario, export
//! the capture, throw the world away, and run the detectors against the
//! re-imported file.
//!
//! # A tour
//!
//! ```
//! use odr_detect::{generate_day, DayOptions, RuleSet};
//!
//! // A day of mixed traffic, generated by running the engine, plus an answer
//! // key that lives somewhere the detectors cannot reach.
//! let day = generate_day(0x0D00_5EED, &DayOptions::default()).unwrap();
//!
//! // All a rule set ever gets is the capture file.
//! let monitor = day.monitor().unwrap();
//! let report = RuleSet::standard().run(&monitor);
//!
//! // Every finding cites the frames that justify it, and the citations hold.
//! assert!(report.evidence_checks(&monitor));
//!
//! // And the score is against ground truth the rule set never saw.
//! let score = day.key().score(&report);
//! assert!(score.is_quiet_on_benign());
//! ```
//!
//! # Module map
//!
//! | Module | What lives there |
//! |---|---|
//! | [`observe`] | [`Monitor`], [`Observation`] — the rule above, as a type |
//! | [`finding`] | [`Finding`], [`Signal`], [`Evidence`], [`Report`] — what a detector says and how a learner checks it |
//! | [`detector`] | [`Detector`], [`RuleSet`] — one rule, and a learner's answer |
//! | [`rules`] | the eight detectors |
//! | [`scenario`] | [`generate_day`] — a day of mixed traffic and its answer key, kept apart |
//! | [`score`] | [`AnswerKey`], [`Score`] — true positives, false positives, time to detection |
//! | [`error`] | [`DetectError`] |
//!
//! # Three things the design insists on
//!
//! **Evidence, always.** A [`Finding`] cites the specific frames that justify
//! it, and [`Evidence::check`] re-reads them. Module 5's point is that a
//! learner can check the reasoning, which is impossible if a rule can say
//! "suspicious" and stop.
//!
//! **Confidence, honestly.** Some of these attacks are visible with certainty,
//! some are visible and undecidable, and some are not visible at all. The
//! [`Confidence`] field says which, and `README.md` carries the full list of
//! what is *not* detectable and why — which is teaching material, not an
//! apology.
//!
//! **The benign case is part of the rule.** Every detector names the benign
//! traffic it was most likely to fire on, and the suite runs it against exactly
//! that traffic and asserts silence. A rule that catches the downgrade and also
//! catches every legacy reader has not solved drill 5.2; it has renamed it.
//!
//! # Constraints it keeps
//!
//! `no_std` + `alloc`, `#![forbid(unsafe_code)]`, builds for
//! `wasm32-unknown-unknown`. Deterministic: seeded randomness only, integer
//! arithmetic, no map iteration, so the same seed gives the same capture, the
//! same report and the same score on every machine (`DESIGN.md` §3). No panics
//! — everything fallible returns [`DetectError`], because a panic in a browser
//! is a dead tab.
//!
//! # Ethics
//!
//! `DESIGN.md` §5: everything here is simulated, and the defensive half exists
//! so that a building owner can run the same range and learn what their own bus
//! would look like under each attack. The key material this crate prints in an
//! evidence note is the already-published Mellon family or a value the scenario
//! generated from a seed; nothing in this workspace has ever seen a real one.

#![no_std]
#![forbid(unsafe_code)]
#![warn(missing_docs)]
#![warn(clippy::all)]

extern crate alloc;

#[cfg(any(test, feature = "std"))]
extern crate std;

pub mod detector;
pub mod error;
pub mod finding;
pub mod observe;
pub mod rules;
pub mod scenario;
pub mod score;

pub use detector::{Detector, RuleSet};
pub use error::{DetectError, Result};
pub use finding::{Confidence, Evidence, Finding, FrameRef, Report, Severity, Signal};
pub use observe::{Monitor, Observation};
pub use rules::{
    badge_events, credential_events, unsolicited_replies, BadgeEvent, CredentialEvent,
    DowngradeDetector, InjectionDetector, KeyDetector, KeysetDetector, PostureDetector,
    ReplayDetector, TrafficDetector, WireDetector,
};
pub use scenario::{generate_day, Day, DayOptions, Episode, EpisodeSpan};
pub use score::{AnswerKey, BenignEvent, Expected, FalsePositive, Hit, Score, Verdict};

#[cfg(test)]
mod tests;
