//! A tiny seeded PRNG, so nonces are reproducible.
//!
//! DESIGN.md section 3 makes determinism a hard requirement: the same scenario
//! must produce the same bytes on every machine, so that CTF flags are stable
//! and a bug is reproducible from a seed alone. This crate therefore contains
//! **no** source of entropy — no `getrandom`, no clock, no `std::time`. A
//! caller who wants "random" nonces seeds this generator.
//!
//! This is SplitMix64. It is not cryptographically secure and must never be
//! used to generate a real key. It exists to make a simulation repeatable.
//! Anything in this crate that needs a nonce takes the nonce as an argument;
//! `SeededRng` is a convenience for the layers above.

/// A deterministic, non-cryptographic 64-bit generator (SplitMix64).
///
/// ```
/// use odr_osdp::rng::SeededRng;
/// let mut a = SeededRng::new(42);
/// let mut b = SeededRng::new(42);
/// assert_eq!(a.nonce8(), b.nonce8());
/// ```
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SeededRng {
    state: u64,
}

impl SeededRng {
    /// Create a generator from a 64-bit seed.
    pub fn new(seed: u64) -> Self {
        Self { state: seed }
    }

    /// Next 64-bit output.
    pub fn next_u64(&mut self) -> u64 {
        self.state = self.state.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    /// Next byte.
    pub fn next_u8(&mut self) -> u8 {
        (self.next_u64() & 0xFF) as u8
    }

    /// Fill a slice with generated bytes.
    pub fn fill(&mut self, out: &mut [u8]) {
        for slot in out.iter_mut() {
            *slot = self.next_u8();
        }
    }

    /// An 8-byte value shaped like an OSDP challenge nonce (RND.A or RND.B).
    pub fn nonce8(&mut self) -> [u8; 8] {
        let mut out = [0u8; 8];
        self.fill(&mut out);
        out
    }

    /// A 16-byte value shaped like an SCBK.
    ///
    /// Reminder: this is *not* a secure key generator. It is here so a drill can
    /// hand a PD a "site key" that is reproducible across runs.
    pub fn key16(&mut self) -> [u8; 16] {
        let mut out = [0u8; 16];
        self.fill(&mut out);
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn same_seed_same_stream() {
        let mut a = SeededRng::new(0xDEAD_BEEF);
        let mut b = SeededRng::new(0xDEAD_BEEF);
        for _ in 0..64 {
            assert_eq!(a.next_u64(), b.next_u64());
        }
    }

    #[test]
    fn different_seeds_diverge() {
        let mut a = SeededRng::new(1);
        let mut b = SeededRng::new(2);
        assert_ne!(a.nonce8(), b.nonce8());
    }

    #[test]
    fn output_is_not_trivially_constant() {
        let mut r = SeededRng::new(7);
        let n = r.nonce8();
        assert!(n.iter().any(|&b| b != n[0]));
    }
}
